source/ManagerBookFront/ManagerBookFront/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManagerBookFront.Controllers
{
    public class BookController : Controller
    {
        // GET: Book
        public ActionResult Index()
        {
            return View();
        }
    }
}

source/ManagerBookFront/ManagerBookFront/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManagerBookFront.Controllers
{
    public class ClientController : Controller
    {
        // GET: Client
        public ActionResult Index()
        {
            return View();
        }
    }
}

source/ManagerBookFront/ManagerBookFront/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManagerBookFront.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

source/ManagerBookFront/ManagerBookFront/Controllers/LendingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManagerBookFront.Controllers
{
    public class LendingController : Controller
    {
        // GET: Lending
        public ActionResult Index()
        {
            return View();
        }
    }
}

source/ManagerBookFront/ManagerBookFront/Controllers/ReturnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManagerBookFront.Controllers
{
    public class ReturnController : Controller
    {
        // GET: Return
        public ActionResult Index()
        {
            return View();
        }
    }
}

source/ManagerBookFront/ManagerBookFront/Views/Book/Index.cshtml
@{
    ViewBag.Title = "Livro";
}
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <div class="container">
        <div class="py-5 text-center">
            <h2>Cadastro de livro</h2>
            <p class="lead">Insira os dados abaixo</p>
        </div>

        <div class="row">
            <div class="col-md-12 order-md-1">
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="name">Nome</label>
                        <input type="text" class="form-control" id="name" placeholder="" value="" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="autor">Autor</label>
                        <input type="text" class="form-control" id="autor" placeholder="" value="" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="isbn">Isbn</label>
                        <input type="text" class="form-control" id="isbn" placeholder="" value="" required>
                    </div>
                </div>

                <button class="btn btn-primary btn-lg" type="submit">Enviar</button>

            </div>
        </div>
        <div class="container">
            <div class="py-5 text-center">
                <hr class="mb-4">
                <h2>Lista de livros</h2>

            </div>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Isbn</th>
                        <th scope="col">Nome</th>
                        <th scope="col">Autor</th>
                        <th scope="col">Açoes</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row"></th>
                        <td></td>
                        <td></td>
                        <td>
                            <button type="button" class="btn btn-success">Editar</button>
                            <button type="button" class="btn btn-danger">Excluir</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

source/ManagerBookFront/ManagerBookFront/Views/Client/Index.cshtml
@{
    ViewBag.Title = "Cliente";
}
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<div class="container">
  <div class="py-5 text-center">   
    <h2>Cadastro de Clientes</h2>
    <p class="lead">Insira os dados abaixo</p>
</div>

  <div class="row">
    <div class="col-md-12 order-md-1">
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="name">Nome</label>
            <input type="text" class="form-control" id="name" placeholder="" value="" required>
          </div>          
        </div>
        <div class="row">
          <div class="col-md-6 mb-3">
            <label for="Email">Email</label>
            <input type="text" class="form-control" id="Email" placeholder="you@example.com" value="" required>
          </div>          
        </div>       
        <button class="btn btn-primary btn-lg" type="submit">Enviar</button>
       
    </div>
  </div>
  <div class="container">
    <div class="py-5 text-center">
      <hr class="mb-4">
      <h2>Lista de livros</h2>
      
    </div>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Açoes</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row"></th>
        <td></td>
        <td><button type="button" class="btn btn-success">Editar</button>
          <button type="button" class="btn btn-danger">Excluir</button>
        </td>
      </tr>
    </tbody>
  </table>
</div>

source/ManagerBookFront/ManagerBookFront/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

source/ManagerBookFront/ManagerBookFront/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

source/ManagerBookFront/ManagerBookFront/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

source/ManagerBookFront/ManagerBookFront/Views/Lending/Index.cshtml
@{
    ViewBag.Title = "Empréstimo de Livro";
}
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <div class="container">
        <div class="py-5 text-center">
            <h2>Empréstimo de livro</h2>
            <p class="lead">Insira os dados abaixo</p>
        </div>

        <div class="row">
            <div class="col-md-12 order-md-1">
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="pessoa">Pessoa</label>
                        <select type="text" class="form-control" id="pessoa"></select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 mb-3">
                        <label for="conditions">Condições</label>
                        <input type="textarea" class="form-control" id="conditions">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 mb-3">
                        <label for="book">Livro</label>
                        <select type="text" class="form-control" id="book"></select>
                    </div>
                </div>
                <div class="row">
                    <div class="custom-control custom-radio">
                        <label class="custom-control-label">Bloqueio</label>
                        <input id="blocked" name="paymentMethod" type="radio" class="custom-control-input" checked>
                    </div>
                </div>
                <button class="btn btn-primary btn-lg" type="submit">Enviar</button>
            </div>

        </div>
        <div class="container">
            <div class="py-5 text-center">
                <hr class="mb-4">
                <h2>Lista de empréstimos de livros</h2>
            </div>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Livro</th>
                        <th scope="col">Pessoa</th>
                        <th scope="col">Condições</th>
                        <th scope="col">Bloqueio</th>
                        <th scope="col">Data do empréstimo</th>
                        <th scope="col">Data da devolução</th>
                        <th scope="col">Açoes</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row"></th>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>
                            <button type="button" class="btn btn-success">Editar</button>
                            <button type="button" class="btn btn-danger">Excluir</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

source/ManagerBookFront/ManagerBookFront/Views/Return/Index.cshtml
@{
    ViewBag.Title = "Devolução de Livro";
}
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <div class="container">
        <div class="py-5 text-center">
            <h2>Devolução de livro</h2>
            <p class="lead">Insira os dados abaixo</p>
        </div>

        <div class="row">
            <div class="col-md-12 order-md-1">
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="date">Data</label>
                        <input type="date" class="form-control" id="date" placeholder="" value="" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8 mb-3">
                        <label for="feedback">Feedback</label>
                        <input type="textarea" class="form-control" id="feedback" placeholder="" value="" required>
                    </div>
                </div>
                <button class="btn btn-primary btn-lg" type="submit">Enviar</button>

            </div>
        </div>
        <div class="container">
            <div class="py-5 text-center">
                <hr class="mb-4">
                <h2>Lista de livros</h2>

            </div>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Data</th>
                        <th scope="col">Feedback</th>
                        <th scope="col">Açoes</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row"></th>
                        <td></td>
                        <td>
                            <button type="button" class="btn btn-success">Editar</button>
                            <button type="button" class="btn btn-danger">Excluir</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

source/ManagerBookFront/ManagerBookFront/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cliente", "Index", "Client")</li>
                    <li>@Html.ActionLink("Livro", "Index", "Book")</li>
                    <li>@Html.ActionLink("Empréstimo de Livro", "Index", "Lending")</li>
                    <li>@Html.ActionLink("Devolução de Livro", "Index", "Return")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>